### PR TITLE
Sfy24

### PR DESCRIPTION
**Pull request by stevenpandrews**
updated with a fresh gtfs file. please check the file and the work.

### CODE REVIEW

**Comment by stevenpandrews** [comment]
@jdelorto-ctps give this a check! the entire script is in the quarto doc. I wanted to be able to share the maps and the code. This was needed when the new UZA boundaries were created. I used a bad dataset initially and it didn't give good values. Hopefully we can get them to replace it with this. FTA wants Directional Route Miles by UZA. This method buffers nearby lines into a single line, then buffers back towards the line to reduce errors, then turns it into a line, which can be used to estimate the "directional" part of the DRM.

**Comment by jdelorto-ctps** [comment]
Looks good to me! The buffer/line methodology was a little confusing but I understood it as I saw the steps sequentially. Otherwise, looks good!

**Review by jdelorto — APPROVED** [review]
Looks good to me! The buffer/line methodology was a little confusing but I understood it as I saw the steps sequentially. Otherwise, looks good!

**Comment by stevenpandrews** [comment]
yeah, it's a bit strange at first, but it mostly works. im not thrilled about how junctions work, but we'll fix that another day.

**Pull request merged**
